# fly.toml app configuration file generated for nextjs-shadcn-template on 2025-04-24T15:00:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextjs-shadcn-template'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

    [[http_service.domains]]
    name = "nextjs-shadcn-template.codeblitz.net"
    catch_all = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
